// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYSMN5jb26SZzh4zs3khmb09x3WpRenMw',
    appId: '1:292854433773:web:f062858bdc327c700fc9e4',
    messagingSenderId: '292854433773',
    projectId: 'instagram-clone-c0fb2',
    authDomain: 'instagram-clone-c0fb2.firebaseapp.com',
    storageBucket: 'instagram-clone-c0fb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuEJZm_xXQvsJg2KFXzfn76mZx94SgPSM',
    appId: '1:292854433773:android:32f1367c2ca37fe20fc9e4',
    messagingSenderId: '292854433773',
    projectId: 'instagram-clone-c0fb2',
    storageBucket: 'instagram-clone-c0fb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCokZ_OcnoX7RQ7DBalHD3rmLVzQHfy_74',
    appId: '1:292854433773:ios:c413ee5b6d4f759c0fc9e4',
    messagingSenderId: '292854433773',
    projectId: 'instagram-clone-c0fb2',
    storageBucket: 'instagram-clone-c0fb2.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCokZ_OcnoX7RQ7DBalHD3rmLVzQHfy_74',
    appId: '1:292854433773:ios:2573e79050ec3c8e0fc9e4',
    messagingSenderId: '292854433773',
    projectId: 'instagram-clone-c0fb2',
    storageBucket: 'instagram-clone-c0fb2.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
